In [1]:
import pandas as pd

In [2]:
latest = pd.read_csv("latest.csv")

In [3]:
latest.head(5)
latest.info()

<class 'pandas.DataFrame'>
RangeIndex: 5730 entries, 0 to 5729
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Tweet Link           5730 non-null   str
 1   Author Handle        5730 non-null   str
 2   Tweet Content        5565 non-null   str
 3   Views                5730 non-null   int64
 4   Likes                5730 non-null   int64
 5   Retweets             5730 non-null   int64
 6   Replies              5730 non-null   int64
 7   Tweet Creation Date  5730 non-null   str
 8   Scraped Date         5730 non-null   str
dtypes: int64(4), str(5)
memory usage: 1.9 MB

In [12]:
lego = latest[latest["Tweet Content"].str.contains("lego", case=False, na=False) | latest["Tweet Content"].str.contains("Explosive Media", case=False, na=False)]
lego.head(50)

,Tweet Link,Author Handle,Tweet Content,Views,Likes,Retweets,Replies,Tweet Creation Date,Scraped Date
650,https://x.com/Person453112/status/204288407861...,Person453112,YouTube bans Explosive Media channel (the one ...,338835,9691,3943,149,2026-04-11T08:34:53+00:00,2026-04-12T14:45:29.484128+00:00
763,https://x.com/Mr_Bhagat08/status/2041135648963...,Mr_Bhagat08,NEW Lego Animation Video from Explosive Media...,43068,1477,482,15,2026-04-06T12:47:15+00:00,2026-04-12T14:26:58.971207+00:00
792,https://x.com/txemasg/status/2041661740056801736,txemasg,RT \n@ExplosiveMediaa\n: Trump has agreed to a...,4,0,147,0,2026-04-07T23:37:45+00:00,2026-04-12T14:25:59.377725+00:00
951,https://x.com/txemasg/status/2042065999323644071,txemasg,NEW Lego Style Music Video from Iran via Pers...,119753,1674,735,22,2026-04-09T02:24:08+00:00,2026-04-12T14:24:59.160707+00:00
954,https://x.com/txemasg/status/2042051887558431135,txemasg,New LEGO clip: “We Will Fulfill Our Duty To L...,38037,1784,726,35,2026-04-09T01:28:04+00:00,2026-04-12T14:24:59.160707+00:00
1112,https://x.com/txemasg/status/2042881987065843784,txemasg,The LEGO videos get better and better,85737,4514,1321,67,2026-04-11T08:26:35+00:00,2026-04-12T14:23:29.540044+00:00
1152,https://x.com/txemasg/status/2042605424432570504,txemasg,"Translated to Spanish, the lyrics are awesome ...",9976,922,611,18,2026-04-10T14:07:37+00:00,2026-04-12T14:23:29.540044+00:00
1160,https://x.com/txemasg/status/2043106684847960514,txemasg,Iranians just published the new very banger LE...,590314,24229,9583,454,2026-04-11T23:19:27+00:00,2026-04-12T14:22:59.448869+00:00
1176,https://x.com/txemasg/status/2043056496104079818,txemasg,NEW : Lego Style Video Tease from Explosive Me...,171613,1658,519,8,2026-04-11T20:00:01+00:00,2026-04-12T14:22:59.448869+00:00
1192,https://x.com/txemasg/status/2043021438542651447,txemasg,Iran just dropped ANOTHER SAVAGE Lego roast “...,58168,635,284,4,2026-04-11T17:40:43+00:00,2026-04-12T14:22:59.448869+00:00
1239,https://x.com/txemasg/status/2043124426007322935,txemasg,You've played your last card. \nYou have no ...,1012,48,24,0,2026-04-12T00:29:57+00:00,2026-04-12T14:22:28.885302+00:00
1242,https://x.com/txemasg/status/2043106537518793020,txemasg,New Iran Lego video: L.I.A.R!\n\nThe music is ...,21528,1320,512,19,2026-04-11T23:18:52+00:00,2026-04-12T14:22:28.885302+00:00
1838,https://x.com/TheBirmingham6/status/2041719028...,TheBirmingham6,The LEGO TACO Movie already dropped.,92973,2359,749,37,2026-04-08T03:25:24+00:00,2026-04-12T13:37:53.248408+00:00
1850,https://x.com/TheBirmingham6/status/2041680678...,TheBirmingham6,"Babe wake up, another Iran Lego movie just dro...",205878,2601,541,41,2026-04-08T00:53:01+00:00,2026-04-12T13:37:53.248408+00:00
1958,https://x.com/TheBirmingham6/status/2042345775...,TheBirmingham6,Iran's Explosive Media with a new Lego Short: ...,12805,391,159,5,2026-04-09T20:55:52+00:00,2026-04-12T13:36:53.183062+00:00
1959,https://x.com/TheBirmingham6/status/2042344037...,TheBirmingham6,NEW Lego Style Video from Explosive Media in ...,10285,379,138,8,2026-04-09T20:48:58+00:00,2026-04-12T13:36:53.183062+00:00
2092,https://x.com/TheBirmingham6/status/2042408876...,TheBirmingham6,"Wake up babe, a new Lego movie just dropped",118124,3575,1022,45,2026-04-10T01:06:36+00:00,2026-04-12T13:36:23.19868+00:00
2098,https://x.com/TheBirmingham6/status/2042380031...,TheBirmingham6,The amount of work and research \n@ExplosiveMe...,36634,1410,305,9,2026-04-09T23:11:59+00:00,2026-04-12T13:36:23.19868+00:00
2139,https://x.com/TheBirmingham6/status/2042778633...,TheBirmingham6,New Lego-Style Movie: The Epstein Curse,62634,2580,899,19,2026-04-11T01:35:53+00:00,2026-04-12T13:35:53.159253+00:00
2206,https://x.com/TheBirmingham6/status/2042588271...,TheBirmingham6,CALLED IT I smelled a LEGO Melania video was ...,332460,11214,4054,132,2026-04-10T12:59:27+00:00,2026-04-12T13:35:53.159253+00:00
2210,https://x.com/TheBirmingham6/status/2042573321...,TheBirmingham6,NEW Lego Style Music Video from Iran via Ukno...,117525,1253,537,14,2026-04-10T12:00:03+00:00,2026-04-12T13:35:53.159253+00:00
2276,https://x.com/TheBirmingham6/status/2042970268...,TheBirmingham6,These Iranian LEGO videos are absolutely bruta...,111735,4625,1038,68,2026-04-11T14:17:23+00:00,2026-04-12T13:35:23.460296+00:00
2355,https://x.com/txemasg/status/2043104833448599818,txemasg,You played your last card.\nNo more aces.\n\nY...,227561,10848,4485,414,2026-04-11T23:12:06+00:00,2026-04-12T13:34:53.398466+00:00
2388,https://x.com/TheBirmingham6/status/2043196117...,TheBirmingham6,If you want to know how absurd and biased the ...,63615,4006,1415,29,2026-04-12T05:14:49+00:00,2026-04-12T13:33:48.360165+00:00
2607,https://x.com/TheBirmingham6/status/2042578004...,TheBirmingham6,Damn. Iran just dropped an A+ level troll on T...,550074,13379,3766,271,2026-04-10T12:18:40+00:00,2026-04-10T14:36:46.683585+00:00
2925,https://x.com/txemasg/status/2042369786051465555,txemasg,New Lego-style video just dropped from \n@Exp...,2521,96,37,1,2026-04-09T22:31:17+00:00,2026-04-10T13:56:46.298382+00:00
2995,https://x.com/txemasg/status/2042316160222285900,txemasg,The Government of Iran made another Lego anima...,26021,1628,954,22,2026-04-09T18:58:11+00:00,2026-04-10T13:36:16.285061+00:00
3061,https://x.com/ani_says1/status/204252874304694...,ani_says1,The Lego’s are spreading!!! \n\nThe UK has ent...,5286,261,89,14,2026-04-10T09:02:55+00:00,2026-04-10T13:35:16.639136+00:00
3087,https://x.com/Paddystinian/status/204235336346...,Paddystinian,New Lego-Style Soundtrack:\nDonald Trump: Mani...,138645,5376,2207,112,2026-04-09T21:26:01+00:00,2026-04-10T13:35:16.639136+00:00
3112,https://x.com/kryptograph3r/status/20425847567...,kryptograph3r,Explosive Media is bringing more awareness tha...,16,1,0,0,2026-04-10T12:45:30+00:00,2026-04-10T13:32:46.563541+00:00
3125,https://x.com/anniefofani/status/2042291220895...,anniefofani,"""I don't think there's another piece of media ...",485,37,2,1,2026-04-09T17:19:05+00:00,2026-04-10T13:32:46.563541+00:00
3127,https://x.com/PaulBec70789962/status/204226445...,PaulBec70789962,Can’t wait for Explosive Media to do an Epstei...,250,14,0,1,2026-04-09T15:32:44+00:00,2026-04-10T13:32:46.563541+00:00
3219,https://x.com/TheBirmingham6/status/2042339848...,TheBirmingham6,"Explosive Media, the original makers of the AI...",60899,3309,1082,33,2026-04-09T20:32:19+00:00,2026-04-10T12:57:45.988464+00:00
3251,https://x.com/Paddystinian/status/204240543370...,Paddystinian,cc \n@DJJamelia\n \n@meero_bham\n \n@Paddyst...,283,2,1,2,2026-04-10T00:52:56+00:00,2026-04-10T12:55:16.356794+00:00
3260,https://x.com/Paddystinian/status/204242127128...,Paddystinian,"In the future when they teach about this war, ...",20868,817,185,40,2026-04-10T01:55:52+00:00,2026-04-10T12:54:46.354997+00:00
3261,https://x.com/Paddystinian/status/204242022381...,Paddystinian,New Lego-Style Soundtrack:\nDonald Trump: Mani...,383,6,1,0,2026-04-10T01:51:42+00:00,2026-04-10T12:54:46.354997+00:00
3264,https://x.com/Paddystinian/status/204241797737...,Paddystinian,New Lebanese Lego-Style Short Movie,839,47,31,0,2026-04-10T01:42:46+00:00,2026-04-10T12:54:46.354997+00:00
3270,https://x.com/TheBirmingham6/status/2042446015...,TheBirmingham6,NEW Lego Style Music Video from Iran via Pers...,108940,2422,1128,28,2026-04-10T03:34:11+00:00,2026-04-10T12:54:16.34579+00:00
3271,https://x.com/DenyThemEssence/status/204235657...,DenyThemEssence,New Lego-Style Soundtrack: \nBeirut. We Won't ...,25105,1327,611,18,2026-04-09T21:38:47+00:00,2026-04-10T12:54:16.34579+00:00
3275,https://x.com/DenyThemEssence/status/204237862...,DenyThemEssence,UK Lego-Style Soundtrack: All We Can Do Is Bla...,43085,2108,939,32,2026-04-09T23:06:24+00:00,2026-04-10T12:53:46.358999+00:00
3280,https://x.com/DenyThemEssence/status/204203859...,DenyThemEssence,Iran just dropped a full LEGO diss track on ...,10707,468,173,9,2026-04-09T00:35:14+00:00,2026-04-10T12:53:46.358999+00:00
3399,https://x.com/txemasg/status/2042388973729763746,txemasg,Our YouTube channel just got taken down again ...,137933,10468,2454,574,2026-04-09T23:47:31+00:00,2026-04-10T08:13:52.658675+00:00
3401,https://x.com/TheJFreakinC/status/204225812590...,TheJFreakinC,BREAKING: Iran just dropped another AI LEGO vi...,615842,9434,2651,220,2026-04-09T15:07:35+00:00,2026-04-10T08:13:52.658675+00:00
3420,https://x.com/misssilluminate/status/203842651...,misssilluminate,"Oil production in Iran may have been reduced, ...",434845,11734,3212,209,2026-03-30T01:22:07+00:00,2026-04-10T08:13:22.328326+00:00
3429,https://x.com/misssilluminate/status/203801114...,misssilluminate,NEW Lego Animation Video from Explosive News ...,519300,18057,7388,382,2026-03-28T21:51:35+00:00,2026-04-10T08:13:22.328326+00:00
3430,https://x.com/misssilluminate/status/203645425...,misssilluminate,"Khamenei Again!\n\n""You thought you took him o...",5723,142,32,4,2026-03-24T14:45:04+00:00,2026-04-10T08:13:22.328326+00:00
3431,https://x.com/misssilluminate/status/203617931...,misssilluminate,: New Lego-Style Animation from Iran\n\nTitled...,34399,895,348,17,2026-03-23T20:32:32+00:00,2026-04-10T08:13:22.328326+00:00
3433,https://x.com/misssilluminate/status/203047288...,misssilluminate,JUST IN : Iranian Media shared a Lego animatio...,1566499,20198,7264,355,2026-03-08T02:37:15+00:00,2026-04-10T08:13:22.328326+00:00
3473,https://x.com/TheBirmingham6/status/2042251499...,TheBirmingham6,The interview with the Lego-style animation te...,39470,1699,494,47,2026-04-09T14:41:15+00:00,2026-04-09T22:16:52.404811+00:00
3479,https://x.com/ExplosiveMediaa/status/204182215...,ExplosiveMediaa,Huge love to everyone who’s been standing with...,33235,995,278,56,2026-04-08T10:15:12+00:00,2026-04-09T22:16:52.404811+00:00

In [5]:
timing = latest.sort_values("Tweet Creation Date", ascending=False)
timing.head(70)

,Tweet Link,Author Handle,Tweet Content,Views,Likes,Retweets,Replies,Tweet Creation Date,Scraped Date
698,https://x.com/Person453112/status/204333504781...,Person453112,RT \n@Melissa_WongMT\n: Buckle up friends - Pr...,0,0,105,0,2026-04-12T14:26:53+00:00,2026-04-12T14:27:28.923774+00:00
1271,https://x.com/txemasg/status/2043329325714260477,txemasg,WSJ: Trump said the U.S. Navy would begin bloc...,594,81,27,10,2026-04-12T14:04:09+00:00,2026-04-12T14:19:48.199748+00:00
654,https://x.com/Person453112/status/204332074134...,Person453112,They are deliberately engineering a crisis.,4778,284,72,21,2026-04-12T13:30:02+00:00,2026-04-12T14:44:59.495297+00:00
655,https://x.com/Person453112/status/204332006329...,Person453112,A blockade to block the blockade that's blocki...,34425,1823,574,168,2026-04-12T13:27:20+00:00,2026-04-12T14:44:59.495297+00:00
656,https://x.com/Person453112/status/204331968957...,Person453112,Buckle up friends - President Kushner is steer...,9356,573,166,36,2026-04-12T13:25:51+00:00,2026-04-12T14:44:59.495297+00:00
...,...,...,...,...,...,...,...,...,...
1266,https://x.com/txemasg/status/2043248992704983530,txemasg,IMPORTANT:\n\nFM \n@Araghchi\n has so far made...,69683,1933,577,20,2026-04-12T08:44:56+00:00,2026-04-12T14:20:17.879898+00:00
2336,https://x.com/moore_lynz45577/status/204324862...,moore_lynz45577,Confirmed: a pathetic puppy - and not only of ...,36816,4220,1543,127,2026-04-12T08:43:28+00:00,2026-04-12T13:34:53.398466+00:00
1677,https://x.com/Soureh_design2/status/2043248332...,Soureh_design2,Things that are so normal to us we don't even ...,9002,368,29,21,2026-04-12T08:42:18+00:00,2026-04-12T13:39:22.988981+00:00
2337,https://x.com/TheBirmingham6/status/2043246100...,TheBirmingham6,Remember that this appalling piece of legislat...,11427,475,308,20,2026-04-12T08:33:26+00:00,2026-04-12T13:34:53.398466+00:00
1267,https://x.com/txemasg/status/2043244426773070103,txemasg,Barbaria: \n\nA bunch of amateurs. \n\nTotally...,26167,2188,621,49,2026-04-12T08:26:47+00:00,2026-04-12T14:20:17.879898+00:00

In [6]:
latest.to_csv("latest_scrape.csv", index=False)

In [7]:
print(timing)

                                             Tweet Link    Author Handle  \
698   https://x.com/Person453112/status/204333504781...     Person453112
1271   https://x.com/txemasg/status/2043329325714260477          txemasg
654   https://x.com/Person453112/status/204332074134...     Person453112
655   https://x.com/Person453112/status/204332006329...     Person453112
656   https://x.com/Person453112/status/204331968957...     Person453112
...                                                 ...              ...
2316  https://x.com/TheBirmingham6/status/1213255150...   TheBirmingham6
2317  https://x.com/TheBirmingham6/status/1213140913...   TheBirmingham6
3640  https://x.com/bibishalom330/status/10705012977...    bibishalom330
4435  https://x.com/LewishamCouncil/status/101957504...  LewishamCouncil
2396  https://x.com/TheBirmingham6/status/7831185713...   TheBirmingham6

                                          Tweet Content  Views  Likes  \
698   RT \n@Melissa_WongMT\n: Buckle up friends - Pr...      0      0
1271  WSJ: Trump said the U.S. Navy would begin bloc...    594     81
654         They are deliberately engineering a crisis.   4778    284
655   A blockade to block the blockade that's blocki...  34425   1823
656   Buckle up friends - President Kushner is steer...   9356    573
...                                                 ...    ...    ...
2316  Iran won the war against ISIL, the war in Syri...      0     38
2317  I wonder with your wide scholarship on Near Mi...      0    602
3640  Have you experienced bullying in academia? Sha...      0      2
4435  Hi, all our parks and open spaces are dealt wi...      0      0
2396  Israeli Minister admits Anti-semitism is a sme...      0    876

      Retweets  Replies        Tweet Creation Date  \
698        105        0  2026-04-12T14:26:53+00:00
1271        27       10  2026-04-12T14:04:09+00:00
654         72       21  2026-04-12T13:30:02+00:00
655        574      168  2026-04-12T13:27:20+00:00
656        166       36  2026-04-12T13:25:51+00:00
...        ...      ...                        ...
2316         9        1  2020-01-04T00:25:43+00:00
2317       107       30  2020-01-03T16:51:47+00:00
3640         1        1  2018-12-06T02:12:52+00:00
4435         0        0  2018-07-18T13:30:08+00:00
2396      1499       88  2016-10-04T01:36:31+00:00

                          Scraped Date
698   2026-04-12T14:27:28.923774+00:00
1271  2026-04-12T14:19:48.199748+00:00
654   2026-04-12T14:44:59.495297+00:00
655   2026-04-12T14:44:59.495297+00:00
656   2026-04-12T14:44:59.495297+00:00
...                                ...
2316  2026-04-12T13:35:23.460296+00:00
2317  2026-04-12T13:35:23.460296+00:00
3640  2026-04-09T20:02:03.609592+00:00
4435  2026-04-09T17:39:07.135616+00:00
2396  2026-04-12T13:33:48.360165+00:00

[5730 rows x 9 columns]

In [8]:

from datetime import datetime

In [9]:
timing['month'] = pd.to_datetime(timing['Tweet Creation Date'], format='ISO8601').dt.month

timing['day'] = pd.to_datetime(timing['Tweet Creation Date'], format='ISO8601').dt.day

timing['hour'] = pd.to_datetime(timing['Tweet Creation Date'], format='ISO8601').dt.hour

timing.head(5)
timing  = timing.to_csv("timing.csv", index=False)